name: 'Tests: node.js'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^6.2 || ^7 || ^8 || ^9.3 || ^10 || >= 11.2'
      type: minors
      command: npm run tests-only

  node:
    name: 'node'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
